name: Code Review

on:
  pull_request:
    types: [opened, reopened, ready_for_review, review_requested, synchronize]
  issue_comment:
    types: [created]

jobs:
  review:
    if: github.event_name == 'pull_request' || github.event.issue.pull_request
    uses: iamvikshan/.github/.github/workflows/pr-agent.yml@main
    permissions:
      contents: write
      pull-requests: write
      issues: write
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
